### ISSUE TITLE
Skocznia Karpacz HS94 K85

### ISSUE THREAD

**Issue by MarcinK50** [SiekamCebule/Open-Ski-Jumping-Fiction-Hill-Pack#2]
Cześć, może dodałbyś Orlinek w Karpaczu? Byłoby fajne :D

**Comment by KonradKrol** [comment]
a nie ma skoczni w Karpaczu w grze? i skąd masz mojego emaila?

niedz., 26 kwi 2020, 11:52 użytkownik Marcin Kowalicki <
notifications@github.com> napisał:

**Comment by MarcinK50** [comment]
Nie sprawdzałem czy jest, a mail jest od githuba zrobiłem issue

pon., 27 kwi 2020, 11:30 użytkownik SiekamCebule <notifications@github.com>
napisał:

**Comment by KonradKrol** [comment]
ok, chyba jest, możesz wejść na discorda i zaproponować skocznie do paczki,
możesz nawet tutaj powiedzieć, powiedz punkt K i HS, i jakieś części
charakterystyczne, czyli typu że sie wysoko leci, jaki próg itp

pon., 27 kwi 2020, 13:15 użytkownik Marcin Kowalicki <
notifications@github.com> napisał:

**Comment by MarcinK50** [comment]
Możesz tutaj zajrzeć
https://pl.m.wikipedia.org/wiki/Orlinek_(skocznia_narciarska) . Napiszę, to
co wyczytałem
K 85
HS 94
Wysokość progu 2,2 m
Nachylenie progu 10°
Nachylenie zeskoku 33°
Długość najazdu 85 m

pon., 27 kwi 2020, 13:29 użytkownik SiekamCebule <notifications@github.com>
napisał:

**Comment by KonradKrol** [comment]
skocznia w Karpaczu jest w grze, możesz napisać jakąś wymyśloną skocznie,
bo robię paczkę do gry.
jak masz discorda to moja nazwa: SiekamCebule#5280

Pozdrawiam

pon., 27 kwi 2020, 14:48 użytkownik Marcin Kowalicki <
notifications@github.com> napisał:
